######## Sidebar ########
# 左上角显示的 logo 区域，包含图标、大标题、副标题
logo:
  avatar: '[{config.avatar}](/dogcare/)' # you can set avatar link in _config.yml or '[https://xxx.png](/about/)'
  title: '[<img no-lazy height="32px" src="https://youke1.picui.cn/s1/2025/07/30/6889820d57f69.png"/>](/dogcare/)' # you can set html tag like: '[<img no-lazy height="32px" src="xxx"/>](/)'
  subtitle: '你好 | ?' # '文字1 | 文字2' (鼠标放上去会切换到文字2)
# 侧边栏主功能导航菜单
# 站点主结构树
site_tree:
  # 博客列表页配置
  index_blog:
    base_dir: blog # 只影响自动生成的页面路径
    menu_id: post # 未在 front-matter 中指定 menu_id 时，layout 为 post 的页面默认使用这里配置的 menu_id
    leftbar: recent # for categories/tags/archives
    rightbar: ghrepo
    nav_tabs: # 近期发布 分类 标签 专栏 归档 and ...
      "新闻": /news/
  # 博客专栏列表页配置
  index_topic:
    base_dir: topic # 只影响自动生成的页面路径
    menu_id: post # 未在 front-matter 中指定 menu_id 时，layout 为 topic 的页面默认使用这里配置的 menu_id
  # 文档列表页配置
  index_wiki:
    base_dir: wiki # 只影响自动生成的页面路径
    menu_id: wiki # 未在 front-matter 中指定 menu_id 时，layout 为 wiki 的页面默认使用这里配置的 menu_id
    leftbar: ghissues, related, recent # for wiki
    rightbar: ghrepo
    nav_tabs:
  # 博客文章内页配置
  home:
    leftbar: welcome, announcement
    rightbar: comment, tagcloud
  post:
    menu_id: post # 未在 front-matter 中指定 menu_id 时，layout 为 post 的页面默认使用这里配置的 menu_id
    leftbar: related, recent # for pages using 'layout:post'
    rightbar: ghrepo, toc
  # 博客专栏文章内页配置
  topic:
    menu_id: post
  # 文档内页配置
  wiki:
    menu_id: wiki # 未在 front-matter 中指定 menu_id 时，layout 为 wiki 的页面默认使用这里配置的 menu_id
    leftbar: tree
    rightbar: ghrepo, toc
  # 错误页配置
  error_page:
    menu_id: post
    "404": "/404.html"
    leftbar: recent
    rightbar: tagcloud
  # 其它自定义页面配置 layout: page
  page:
    leftbar: recent
    rightbar: timeline

open_graph:
  enable: false
  twitter_id: # for open_graph meta

article:
  type: tech # tech/story: story类文字和段落间增距大。
  auto_cover: false # 根据tags在线搜索封面
  auto_description: 20 # 生成摘要的字
  related_posts:
    enable: true
    title: 您可能感兴趣的文章
    max_count: 2
  license: false
  share: [wechat, weibo, email, link]
